# Generated by Django 2.1.7 on 2019-03-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0003_auto_20181117_2328_squashed_0004_auto_20190227_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.ForeignKey(help_text='The account the charge was made on behalf of. Null here indicates that this value was never set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='djstripe.Account'),
        ),
    ]
