# Generated by Django 2.2 on 2019-11-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_sub', to='djstripe.Subscription'),
        ),
    ]
